### ISSUE TITLE
Compilation Issues

### ISSUE THREAD

**Issue by OdinVex** [TTK-qmmp/qmmp-psf#1]
Compilation issues, it is looking for `~/plugins.pri` (no reason to) and tries using `/Input`. `Makefile` needs redoing, unable to compile. Why the relative assumption of `plugins.pri`?

Edit: https://github.com/TTK-qmmp/qmmp-psf/commit/8c07034103089b9a63f7e4e214c31cf393e31f99 would be why, environmental variables aren't being set by anything and the hard-coded `plugins.pri` bit isn't explained.

Edit: Apparently this needs to be moved into qmmp's src/plugins/Input/ folder and then compiled. I had to remove `-lqmmp` from the `Makefile`, though.

**Comment by Greedysky** [comment]
Fixed
